[package]
name = "rust-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
itertools = "0.13.0"
log = "0.4.22"
quote = "1.0.36"
rand = "0.8.5"
syn = { version = "2.0.66", features = ["full", "extra-traits", "visit"] }
